### ISSUE TITLE
Run attacks against target depth / size

### ISSUE THREAD

**Issue by nikkolasg** [filecoin-project/drg-attacks#21]
We don't need many points to be able to draw the curve of the tuples (e,d) as shown in the bucket sample graph in the porep short paper. We only care about when 0.10 <= S <= 0.30 and 0.15 <= d <= 0.25 because that is what we use so far in the analysis. ( we actually only use one of these three values but best to be able to reason about the evolution if cwe change one or another parameter).

+ Fix |S| = {0.10n, 0.20n, 0.30n} -> find the best d we can have (the smallest)
+ Fix d = 0.25n, 0.20n, 0.15n} -> find the best S we can have (the smallest)

That should be the baseline on which to reward the DRG game bounty

**Comment by schomatis** [comment]
I'm interpreting _graph_ here as some kind of attack quality graph as the figures from the paper (if this is the case ignore the previous question).

**Comment by schomatis** [comment]
Could you more clearly define ranges and intervals to sample target depths and set `S` sizes? It doesn't have to be anything definitive, this can be adjusted once we have some results, but to have a ballpark figure. Alternatively I can just hardcode the values to the ones in the original post.

**Comment by nikkolasg** [comment]
> > Instead of generating the whole graph,
> 
> By graph you mean the bucket sample graph `g`? And if so, how would we _not_ fully generate it?

Sorry, clash of terminology here: I meant we don't need to to many points to be able to draw the curve of the tuples (e,d) as shown in the bucket sample graph in the porep short paper. We only care about when 0.10 <= S <= 0.30 and 0.15 <= d <= 0.25 because that is what we use so far in the analysis. ( we actually only use one of these three values but best to be able to reason about the evolution if cwe change one or another parameter).

**Comment by nikkolasg** [comment]
This issue should be solved only after #20 as to get an averaged result.

**Comment by schomatis** [comment]
I think we can interface both issues expanding the `attack` API to have an extra argument with the number of runs,

```
fn attack(g: &mut Graph, r: DepthReduceSet, runs: usize) {
```

In the meanwhile I'll work with this signature with an (unused) value of `runs` equal to 1.

**Comment by schomatis** [comment]
Done in https://github.com/filecoin-project/drg-attacks/pull/23.
